(window.FLOU_FILES = window.FLOU_FILES || {})['data_en.js'] = '37';   /* verze souboru — kontrola, že jsou na webu všechny soubory stejné verze */
/* ============ CARD DATA — ENGLISH ============
   Stejné pořadí jako v data.js (index karty = stejná otázka).
   Karty šance jsou podle klíče efektu. */
const QUESTIONS_EN = {
  red: [
    "Would you like to have a superpower? If so, which one? Explain your answer.",
    "What was the biggest illusion you later found out wasn't true?",
    "What would you do if you were the last person on the planet?",
    "What would you like to teach people?",
    "What would you never do in your life, even if someone offered you a billion?",
    "What would you like to leave behind or pass on?",
    "What would you do if you woke up one morning in the body of the opposite sex?",
    "What frightening thing has happened to you?",
    "What do you consider a waste of time?",
    "What is your passion? Is there anything you would trade it for?",
    "What is your bad habit?",
    "What is currently your biggest problem or challenge?",
    "What do you need to do to get a good night's sleep?",
    "What do you admire in people?",
    "What do you expect from a relationship with another person?",
    "What do you consider success?",
    "What does abundance mean to you?",
    "What does love mean to you?",
    "What does uncertainty mean to you? How do you perceive it? Can you be certain of anything?",
    "What does happiness mean to you?",
    "What do you think gets overlooked and doesn't get enough attention?",
    "What brings you the most joy?",
    "What drains the most energy from you during the day?",
    "What do you find sad?",
    "What are you interested in at the moment?",
    "What can wind you up so much that it makes your hair stand on end?",
    "What makes you step out of your comfort zone?",
    "What motivates you?",
    "What really grabs your attention?",
    "What really pisses you off?",
    "What stresses you out?",
    "What makes you feel calm?",
    "What fills you with excitement?",
    "Is there anything you can't imagine your day without?",
    "Is there an activity or hobby you used to love but stopped doing?",
    "Is there a state in life that you would like to reach?",
    "What would your dream day look like?",
    "What would your ideal date look like?",
    "What do you think the world would look like without art?",
    "What would your dream planet to live on look like?",
    "How would you define yourself?",
    "How would you describe the state in which you feel happy?",
    "How would you like to spend the last day of your life?",
    "What do you think a real man and a real woman are like? Does that matter to you at all, or is it more about their character?",
    "How do you deal with stress in the long term?",
    "How do you deal with stress in the short term?",
    "How do you deal with making a mistake? Do you learn from it?",
    "What do you think our world will look like in 50 years?",
    "What trait in people can't you stand?",
    "What would you like to do but for some reason can't?",
    "What was your first job or summer job, and what did you spend your first earnings on?",
    "What was your childhood like? What did you enjoy about it?",
    "What are your interests?",
    "What is your vision for the future?",
    "What things, people and environments have shaped you the most?",
    "What is the biggest trouble you have ever got into?",
    "What is your daily ritual?",
    "What is your favourite pub, café or restaurant?",
    "What feeling does the word \"nature\" evoke in you?",
    "What embarrassing thing has happened to you?",
    "What message would you put in a time capsule for future generations?",
    "What animal would you like to be, and why?",
    "Who is your hero, and for which qualities did you choose them?",
    "Who or what impresses you?",
    "Who or what can make you laugh?",
    "When and where do you feel content, and why?",
    "When did you last put your life at risk?",
    "When were you at your lowest in life? What helped you, and what did you learn from it?",
    "If you could step into the story of any film, which one would it be and what would you do in it?",
    "If you could wake up at any point in history, where and when would it be, and why?",
    "If you were given £10 million to throw the best party ever, what would it be like?",
    "If you could change something about your body and mind, what would you change?",
    "If you had the chance to change something in this world, what would it be?",
    "If you could give a speech broadcast on every TV channel, what would you tell people?",
    "If you had three months left to live, how would you spend them?",
    "What is the most unexpected thing or situation you have experienced?",
    "Which activity or activities do you hate?",
    "What was the longest minute of your life?",
    "What funny memory comes to mind right now?",
    "Which objects are the most valuable to you?",
    "Which qualities do you value in other people?",
    "Do you like the place where you live?",
    "What don't you have the courage to do?",
    "What do you base your decisions on (reason or emotion)?",
    "What do you think trust is based on?",
    "Do you plan your day, or do you let it flow?",
    "Describe the first memory that comes to mind after reading this question.",
    "Share one life hack you have discovered.",
    "What would you like to be the best in the world at, and why?",
    "In what way do you think you are exceptional?",
    "Recall one of your dreams and tell the others about it.",
    "Name at least three of your positive qualities.",
    "Do you follow any religion? Explain your answer.",
    "Do you believe in some higher principle, such as God or the Universe? If so, why?",
    "Do you believe in coincidence? Explain your answer.",
    "Have you ever missed an opportunity and regretted it afterwards? What was it?",
    "What are you afraid of (e.g. spiders, snakes)?",
    "What would you do with your time if there were no internet and no electricity?",
    "What do you put the most effort into in your life?",
    "Tell us about a situation after which everything changed.",
    "Are you living your life the way you want to? Would you change anything about it? What would you like to improve about yourself?"
  ],
  blue: [
    "What is the first thing you would save if your home were on fire?",
    "What would you like to learn?",
    "What is the most expensive item in your wardrobe (shoes and accessories count)?",
    "What is the most expensive thing you have ever bought?",
    "What do you like to read (e.g. books, newspapers, Instagram posts)?",
    "What do you collect?",
    "What went well for you today?",
    "What made you laugh recently?",
    "What made you cry recently?",
    "What has caught your attention lately?",
    "Which TV, online or radio show would you like to be invited on?",
    "What name would you like to have?",
    "What is the longest you have ever gone without sleep?",
    "How do you procrastinate most often?",
    "How are you feeling today?",
    "Which character would you like to play in a film?",
    "Which social network do you use the most?",
    "What would you like to own?",
    "What is the last thing you bought (apart from food)?",
    "Which app do you use most on your phone?",
    "What do you spend the most time doing (apart from sleeping, eating and working)?",
    "What is your favourite colour?",
    "What is your favourite board game or video game?",
    "Who is your favourite film or TV character?",
    "What is your favourite way to relax?",
    "What is your favourite catchphrase or quote?",
    "What was your favourite toy as a child?",
    "What is your favourite band?",
    "What is your favourite cuisine?",
    "What is your favourite flower?",
    "What is your favourite fairy tale?",
    "What is your favourite song?",
    "What is your favourite sweet treat?",
    "What is your favourite temperature (within a 5-degree range)?",
    "Who is your favourite female artist?",
    "What is your favourite thing?",
    "What is your favourite scent?",
    "What is your favourite website?",
    "What is your favourite vegetable?",
    "What is your favourite country?",
    "What is your favourite car brand?",
    "What is your favourite shoe brand?",
    "What is your favourite electronics brand?",
    "What is your favourite clothing brand?",
    "What is your favourite activity?",
    "What is your typical breakfast?",
    "What is your typical dinner?",
    "What is your favourite time of day?",
    "What was the last meal you cooked?",
    "What is your favourite food?",
    "What is your favourite place?",
    "What is your favourite fruit?",
    "What is your favourite season?",
    "What is your favourite animal?",
    "What is your favourite number?",
    "What is your star sign?",
    "What are your favourite nuts?",
    "What is the worst food you have ever tasted?",
    "What job would you like to try?",
    "What did you want to be when you were little?",
    "What would you call your own restaurant?",
    "What present have you received recently?",
    "What film have you watched recently?",
    "What is your most interesting holiday souvenir?",
    "What is your favourite day of the week?",
    "What is your favourite kind of meat?",
    "What is your favourite gadget?",
    "What is your favourite film?",
    "What is your favourite musical instrument?",
    "What is your favourite summer sport?",
    "What is your favourite drink?",
    "What is your favourite TV series?",
    "Who is your favourite athlete?",
    "What is your favourite dance?",
    "Who is your favourite male artist?",
    "What is your favourite winter sport?",
    "What is your favourite way to get around?",
    "Which school subject did you find interesting?",
    "What kind of holiday do you prefer?",
    "What is an interesting present you have received?",
    "Is there anything you would have done differently today?",
    "Where would you like to live?",
    "Where do you like to shop?",
    "When were you last stressed?",
    "When did you last exercise?",
    "When did you last make someone happy?",
    "If you had your own TV show, what would it be about?",
    "If you were to make a present for the person closest to you, what would it be?",
    "If you were to start your own brand, what would you sell?",
    "How did you feel when you woke up today?",
    "Who do you like to follow (e.g. on Facebook, Instagram, podcasts)?",
    "On average, how many hours a day do you spend on your phone?",
    "On average, how many hours do you sleep?",
    "How many siblings do you have?",
    "What is the farthest destination you have ever visited?",
    "What job would you never want to do?",
    "What situation has moved you recently?",
    "What concert have you been to recently?",
    "What animal would you like to ride?",
    "How do you like your eggs?",
    "What thing or situation have you been grateful for recently?"
  ],
  yellow: [
    "What is your opinion on organic food?",
    "What is your opinion on Christmas?",
    "What is your opinion on adrenaline sports?",
    "What is your opinion on lifestyle diseases?",
    "What is your opinion on demonstrations?",
    "What is your opinion on design?",
    "What is your opinion on discipline?",
    "What is your opinion on theatre / cinema?",
    "What is your opinion on goodness?",
    "What is your opinion on volunteering?",
    "What is your opinion on euthanasia?",
    "What is your opinion on extroverts / introverts?",
    "What is your opinion on people into the esoteric / sceptics?",
    "What is your opinion on fast food and bistros?",
    "What is your opinion on feminism?",
    "What is your opinion on gentlemen?",
    "What is your opinion on global warming?",
    "What is your opinion on homosexuality?",
    "What is your opinion on horror films?",
    "What is your opinion on horoscopes?",
    "What is your opinion on humour?",
    "What is your opinion on the internet?",
    "What is your opinion on investing?",
    "What is your opinion on karma?",
    "What is your opinion on classical music?",
    "What is your opinion on caffeine?",
    "What is your opinion on communication?",
    "What is your opinion on communism?",
    "What is your opinion on people released from prison?",
    "What is your opinion on love at first sight?",
    "What is your opinion on manipulation?",
    "What is your opinion on materialism?",
    "What is your opinion on meditation?",
    "What is your opinion on aliens?",
    "What is your opinion on minimalism?",
    "What is your opinion on supernatural beings?",
    "What is your opinion on shopping?",
    "What is your opinion on birthday parties?",
    "What is your opinion on heaven and hell?",
    "What is your opinion on immortality?",
    "What is your opinion on buying digital vs. physical content?",
    "What is your opinion on low / high self-esteem?",
    "What is your opinion on rest?",
    "What is your opinion on optimism / pessimism?",
    "What is your opinion on personal growth?",
    "What is your opinion on slavery?",
    "What is your opinion on vaccination?",
    "What is your opinion on counterfeits?",
    "What is your opinion on polyamory (consensual non-monogamous relationships)?",
    "What is your opinion on working out / cold-water swimming?",
    "What is your opinion on working in a team / working alone?",
    "What is your opinion on working from home?",
    "What is your opinion on handwriting / typing on a computer?",
    "What is your opinion on prejudice?",
    "What is your opinion on speeding when driving?",
    "What is your opinion on natural disasters?",
    "What is your opinion on natural healing?",
    "What is your opinion on loans?",
    "What is your opinion on racism?",
    "What is your opinion on reincarnation?",
    "What is your opinion on advertising?",
    "What is your opinion on robots / artificial intelligence?",
    "What is your opinion on solitude?",
    "What is your opinion on the elderly?",
    "What is your opinion on smartphones?",
    "What is your opinion on death?",
    "What is your opinion on dreams?",
    "What is your opinion on social media?",
    "What is your opinion on privacy?",
    "What is your opinion on current politics?",
    "What is your opinion on sleeping under the stars?",
    "What is your opinion on spirituality?",
    "What is your opinion on freedom?",
    "What is your opinion on the education system in your country?",
    "What is your opinion on taboo topics?",
    "What is your opinion on lucky charms?",
    "What is your opinion on television / radio?",
    "What is your opinion on tattoos / piercings?",
    "What is your opinion on silence?",
    "What is your opinion on the death penalty?",
    "What is your opinion on sorting waste for recycling?",
    "What is your opinion on recognition?",
    "What is your opinion on vegetarianism / veganism?",
    "What is your opinion on the universe?",
    "What is your opinion on virtual reality?",
    "What is your opinion on how we perceive time?",
    "What is your opinion on faith?",
    "What is your opinion on \"free\" stuff?",
    "What is your opinion on workaholism?",
    "What is your opinion on xenophobia?",
    "What is your opinion on YouTubers and influencers (people with influence and reach)?",
    "What is your opinion on illegal drugs (marijuana, meth, cocaine, etc.)?",
    "What is your opinion on the healthcare system / doctors?",
    "What is your opinion on a healthy lifestyle?",
    "What is your opinion on evil?",
    "What is your opinion on change?",
    "What is your opinion on air pollution?",
    "What is your opinion on addiction?",
    "What is your opinion on success?",
    "What is your opinion on jealousy?",
    "What is your opinion on \"trendy\" things?"
  ]
};

const CHANCE_EN = {
  lose_all: "You lose all your cards.",
  lose_all_unless_red: "You lose all your cards unless you roll red.",
  go_again: "You go again.",
  change_color: "You may change the colour of your question card.",
  right_answers: "The player on your right answers the question. If they don't answer, they lose a card of that colour.",
  reverse: "The direction of play reverses.",
  skip_next: "You sit this turn out.",
  steal: "You may steal one card of your choice from another player.",
  trade_one_for_one: "You may swap one of your cards for a card of another colour, if you want to.",
  trade_two_for_one: "You may swap one of your cards for a card of another colour, if you want to.",
  everyone_red: "Everyone answers a red question."
};
